# Generated by Django 5.2.1 on 2025-05-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RainfallApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rainfalllist",
            name="Input",
        ),
        migrations.RemoveField(
            model_name="rainfalllist",
            name="Output",
        ),
        migrations.AddField(
            model_name="rainfalllist",
            name="Area",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="rainfalllist",
            name="Precipitation",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="rainfalllist",
            name="SurfaceCoefficient",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="rainfalllist",
            name="VolumeOfRunoff",
            field=models.CharField(default="", max_length=100),
        ),
    ]
